plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  tag:Project: catalogix
  instance-state-name: running
  # This prevent Ansible from targeting stopped or termminated instances

keyed_groups:
  - key: tags.Role
    prefix: ""
    separator: ""
    # Setting prefix to "" and separator to "" means the group name is exactly the tag value: "jenkins" and "sonarqube".

hostnames:
  - public-ip-address
    # Ansible runs from outside AWS (developer laptop or CI), so it needs the public IP. EC2 instances are now in public subnets with public IPs assigned

compose:
  - public-ip-address
